pub struct PacketIds {
    pub protocol_version: i32,
    pub login_disconnect: i32,
    pub encryption_request: i32,
    pub login_success: i32,
    pub set_compression: i32,
    pub login_acknowledged: Option<i32>,
    pub configuration_finish_client: Option<i32>,
    pub configuration_finish_server: Option<i32>,
    pub configuration_disconnect: Option<i32>,
    pub play_disconnect: i32,
    pub play_keep_alive_client: i32,
    pub play_keep_alive_server: i32,
    pub player_info: i32,
    pub player_remove: Option<i32>,
    pub teams: i32,
}

pub const PACKET_ID_TABLE: &[PacketIds] = &[
    PacketIds {
        protocol_version: 47,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 64,
        play_keep_alive_client: 0,
        play_keep_alive_server: 0,
        player_info: 56,
        player_remove: None,
        teams: 62,
    },
    PacketIds {
        protocol_version: 76,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 25,
        play_keep_alive_client: 31,
        play_keep_alive_server: 10,
        player_info: 45,
        player_remove: None,
        teams: 64,
    },
    PacketIds {
        protocol_version: 107,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 31,
        play_keep_alive_server: 11,
        player_info: 45,
        player_remove: None,
        teams: 65,
    },
    PacketIds {
        protocol_version: 109,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 31,
        play_keep_alive_server: 11,
        player_info: 45,
        player_remove: None,
        teams: 65,
    },
    PacketIds {
        protocol_version: 110,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 31,
        play_keep_alive_server: 11,
        player_info: 45,
        player_remove: None,
        teams: 65,
    },
    PacketIds {
        protocol_version: 201,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 31,
        play_keep_alive_server: 11,
        player_info: 45,
        player_remove: None,
        teams: 65,
    },
    PacketIds {
        protocol_version: 210,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 31,
        play_keep_alive_server: 11,
        player_info: 45,
        player_remove: None,
        teams: 65,
    },
    PacketIds {
        protocol_version: 304,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 31,
        play_keep_alive_server: 11,
        player_info: 45,
        player_remove: None,
        teams: 65,
    },
    PacketIds {
        protocol_version: 315,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 31,
        play_keep_alive_server: 11,
        player_info: 45,
        player_remove: None,
        teams: 65,
    },
    PacketIds {
        protocol_version: 316,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 31,
        play_keep_alive_server: 11,
        player_info: 45,
        player_remove: None,
        teams: 65,
    },
    PacketIds {
        protocol_version: 321,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 27,
        play_keep_alive_client: 32,
        play_keep_alive_server: 12,
        player_info: 46,
        player_remove: None,
        teams: 67,
    },
    PacketIds {
        protocol_version: 327,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 27,
        play_keep_alive_client: 32,
        play_keep_alive_server: 12,
        player_info: 46,
        player_remove: None,
        teams: 67,
    },
    PacketIds {
        protocol_version: 335,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 31,
        play_keep_alive_server: 12,
        player_info: 45,
        player_remove: None,
        teams: 67,
    },
    PacketIds {
        protocol_version: 338,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 31,
        play_keep_alive_server: 11,
        player_info: 46,
        player_remove: None,
        teams: 68,
    },
    PacketIds {
        protocol_version: 340,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 31,
        play_keep_alive_server: 11,
        player_info: 46,
        player_remove: None,
        teams: 68,
    },
    PacketIds {
        protocol_version: 351,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 27,
        play_keep_alive_client: 32,
        play_keep_alive_server: 11,
        player_info: 47,
        player_remove: None,
        teams: 69,
    },
    PacketIds {
        protocol_version: 393,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 27,
        play_keep_alive_client: 33,
        play_keep_alive_server: 14,
        player_info: 48,
        player_remove: None,
        teams: 71,
    },
    PacketIds {
        protocol_version: 401,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 27,
        play_keep_alive_client: 33,
        play_keep_alive_server: 14,
        player_info: 48,
        player_remove: None,
        teams: 71,
    },
    PacketIds {
        protocol_version: 404,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 27,
        play_keep_alive_client: 33,
        play_keep_alive_server: 14,
        player_info: 48,
        player_remove: None,
        teams: 71,
    },
    PacketIds {
        protocol_version: 477,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 32,
        play_keep_alive_server: 15,
        player_info: 51,
        player_remove: None,
        teams: 75,
    },
    PacketIds {
        protocol_version: 480,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 32,
        play_keep_alive_server: 15,
        player_info: 51,
        player_remove: None,
        teams: 75,
    },
    PacketIds {
        protocol_version: 490,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 32,
        play_keep_alive_server: 15,
        player_info: 51,
        player_remove: None,
        teams: 75,
    },
    PacketIds {
        protocol_version: 498,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 32,
        play_keep_alive_server: 15,
        player_info: 51,
        player_remove: None,
        teams: 75,
    },
    PacketIds {
        protocol_version: 573,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 27,
        play_keep_alive_client: 33,
        play_keep_alive_server: 15,
        player_info: 52,
        player_remove: None,
        teams: 76,
    },
    PacketIds {
        protocol_version: 575,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 27,
        play_keep_alive_client: 33,
        play_keep_alive_server: 15,
        player_info: 52,
        player_remove: None,
        teams: 76,
    },
    PacketIds {
        protocol_version: 578,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 27,
        play_keep_alive_client: 33,
        play_keep_alive_server: 15,
        player_info: 52,
        player_remove: None,
        teams: 76,
    },
    PacketIds {
        protocol_version: 709,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 27,
        play_keep_alive_client: 33,
        play_keep_alive_server: 15,
        player_info: 52,
        player_remove: None,
        teams: 77,
    },
    PacketIds {
        protocol_version: 710,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 27,
        play_keep_alive_client: 33,
        play_keep_alive_server: 15,
        player_info: 52,
        player_remove: None,
        teams: 77,
    },
    PacketIds {
        protocol_version: 735,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 32,
        play_keep_alive_server: 16,
        player_info: 51,
        player_remove: None,
        teams: 76,
    },
    PacketIds {
        protocol_version: 736,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 32,
        play_keep_alive_server: 16,
        player_info: 51,
        player_remove: None,
        teams: 76,
    },
    PacketIds {
        protocol_version: 751,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 25,
        play_keep_alive_client: 31,
        play_keep_alive_server: 16,
        player_info: 50,
        player_remove: None,
        teams: 76,
    },
    PacketIds {
        protocol_version: 753,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 25,
        play_keep_alive_client: 31,
        play_keep_alive_server: 16,
        player_info: 50,
        player_remove: None,
        teams: 76,
    },
    PacketIds {
        protocol_version: 754,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 25,
        play_keep_alive_client: 31,
        play_keep_alive_server: 16,
        player_info: 50,
        player_remove: None,
        teams: 76,
    },
    PacketIds {
        protocol_version: 755,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 33,
        play_keep_alive_server: 15,
        player_info: 54,
        player_remove: None,
        teams: 85,
    },
    PacketIds {
        protocol_version: 756,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 33,
        play_keep_alive_server: 15,
        player_info: 54,
        player_remove: None,
        teams: 85,
    },
    PacketIds {
        protocol_version: 757,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 33,
        play_keep_alive_server: 15,
        player_info: 54,
        player_remove: None,
        teams: 85,
    },
    PacketIds {
        protocol_version: 758,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 33,
        play_keep_alive_server: 15,
        player_info: 54,
        player_remove: None,
        teams: 85,
    },
    PacketIds {
        protocol_version: 759,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 23,
        play_keep_alive_client: 30,
        play_keep_alive_server: 17,
        player_info: 52,
        player_remove: None,
        teams: 85,
    },
    PacketIds {
        protocol_version: 760,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 25,
        play_keep_alive_client: 32,
        play_keep_alive_server: 18,
        player_info: 55,
        player_remove: None,
        teams: 88,
    },
    PacketIds {
        protocol_version: 761,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 23,
        play_keep_alive_client: 31,
        play_keep_alive_server: 17,
        player_info: 54,
        player_remove: Some(53),
        teams: 86,
    },
    PacketIds {
        protocol_version: 762,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 35,
        play_keep_alive_server: 18,
        player_info: 58,
        player_remove: Some(57),
        teams: 90,
    },
    PacketIds {
        protocol_version: 763,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: None,
        configuration_finish_client: None,
        configuration_finish_server: None,
        configuration_disconnect: None,
        play_disconnect: 26,
        play_keep_alive_client: 35,
        play_keep_alive_server: 18,
        player_info: 58,
        player_remove: Some(57),
        teams: 90,
    },
    PacketIds {
        protocol_version: 764,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(2),
        configuration_finish_server: Some(2),
        configuration_disconnect: Some(1),
        play_disconnect: 27,
        play_keep_alive_client: 36,
        play_keep_alive_server: 20,
        player_info: 60,
        player_remove: Some(59),
        teams: 92,
    },
    PacketIds {
        protocol_version: 765,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(2),
        configuration_finish_server: Some(2),
        configuration_disconnect: Some(1),
        play_disconnect: 27,
        play_keep_alive_client: 36,
        play_keep_alive_server: 21,
        player_info: 60,
        player_remove: Some(59),
        teams: 94,
    },
    PacketIds {
        protocol_version: 766,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(3),
        configuration_finish_server: Some(3),
        configuration_disconnect: Some(2),
        play_disconnect: 29,
        play_keep_alive_client: 38,
        play_keep_alive_server: 24,
        player_info: 62,
        player_remove: Some(61),
        teams: 96,
    },
    PacketIds {
        protocol_version: 767,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(3),
        configuration_finish_server: Some(3),
        configuration_disconnect: Some(2),
        play_disconnect: 29,
        play_keep_alive_client: 38,
        play_keep_alive_server: 24,
        player_info: 62,
        player_remove: Some(61),
        teams: 96,
    },
    PacketIds {
        protocol_version: 768,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(3),
        configuration_finish_server: Some(3),
        configuration_disconnect: Some(2),
        play_disconnect: 29,
        play_keep_alive_client: 39,
        play_keep_alive_server: 26,
        player_info: 64,
        player_remove: Some(63),
        teams: 103,
    },
    PacketIds {
        protocol_version: 769,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(3),
        configuration_finish_server: Some(3),
        configuration_disconnect: Some(2),
        play_disconnect: 29,
        play_keep_alive_client: 39,
        play_keep_alive_server: 26,
        player_info: 64,
        player_remove: Some(63),
        teams: 103,
    },
    PacketIds {
        protocol_version: 770,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(3),
        configuration_finish_server: Some(3),
        configuration_disconnect: Some(2),
        play_disconnect: 28,
        play_keep_alive_client: 38,
        play_keep_alive_server: 26,
        player_info: 63,
        player_remove: Some(62),
        teams: 102,
    },
    PacketIds {
        protocol_version: 771,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(3),
        configuration_finish_server: Some(3),
        configuration_disconnect: Some(2),
        play_disconnect: 28,
        play_keep_alive_client: 38,
        play_keep_alive_server: 27,
        player_info: 63,
        player_remove: Some(62),
        teams: 102,
    },
    PacketIds {
        protocol_version: 772,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(3),
        configuration_finish_server: Some(3),
        configuration_disconnect: Some(2),
        play_disconnect: 28,
        play_keep_alive_client: 38,
        play_keep_alive_server: 27,
        player_info: 63,
        player_remove: Some(62),
        teams: 102,
    },
    PacketIds {
        protocol_version: 773,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(3),
        configuration_finish_server: Some(3),
        configuration_disconnect: Some(2),
        play_disconnect: 32,
        play_keep_alive_client: 43,
        play_keep_alive_server: 27,
        player_info: 68,
        player_remove: Some(67),
        teams: 107,
    },
    PacketIds {
        protocol_version: 774,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(3),
        configuration_finish_server: Some(3),
        configuration_disconnect: Some(2),
        play_disconnect: 32,
        play_keep_alive_client: 43,
        play_keep_alive_server: 27,
        player_info: 68,
        player_remove: Some(67),
        teams: 107,
    },
    PacketIds {
        protocol_version: 775,
        login_disconnect: 0,
        encryption_request: 1,
        login_success: 2,
        set_compression: 3,
        login_acknowledged: Some(3),
        configuration_finish_client: Some(3),
        configuration_finish_server: Some(3),
        configuration_disconnect: Some(2),
        play_disconnect: 32,
        play_keep_alive_client: 44,
        play_keep_alive_server: 28,
        player_info: 70,
        player_remove: Some(69),
        teams: 109,
    },
];

pub fn lookup(protocol_version: i32) -> Option<&'static PacketIds> {
    PACKET_ID_TABLE
        .iter()
        .find(|row| row.protocol_version == protocol_version)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_sorted_and_has_no_duplicate_versions() {
        let mut last = i32::MIN;
        for row in PACKET_ID_TABLE {
            assert!(row.protocol_version > last);
            last = row.protocol_version;
        }
    }

    #[test]
    fn looks_up_known_versions() {
        assert!(lookup(47).is_some());
        assert!(lookup(765).is_some());
        assert!(lookup(776).is_none());
    }

    #[test]
    fn configuration_state_fields_present_only_from_1_20_2_onward() {
        let pre = lookup(763).unwrap();
        assert!(pre.login_acknowledged.is_none());
        let post = lookup(764).unwrap();
        assert!(post.login_acknowledged.is_some());
    }
}
